options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };

    allow-query { any; };

    recursion yes;

    forwarders {
        8.8.8.8;
        1.1.1.1;
    };

    dnssec-validation no;
};

zone "empresa.test" {
    type master;
    file "/etc/bind/db.empresa.test";
};

zone "20.172.in-addr.arpa" {
    type master;
    file "/etc/bind/db.172.20.0";
};