default-lease-time 600;
max-lease-time 7200;

authoritative;

default-lease-time 600;
max-lease-time 7200;

option domain-name "lab.local";

subnet 192.168.50.0 netmask 255.255.255.0 {

    range 192.168.50.100 192.168.50.200;

    option subnet-mask 255.255.255.0;
    option broadcast-address 192.168.50.255;
    option routers 192.168.50.1;

    option domain-name "dhcp-lab.local";
    option domain-name-servers 192.168.50.2;
}

subnet 10.10.0.0 netmask 255.255.255.0 {

    range 10.10.0.100 10.10.0.200;

    option subnet-mask 255.255.255.0;
    option broadcast-address 10.10.0.255;
    option routers 10.10.0.1;

    option domain-name "dhcp-lab.local";
    option domain-name-servers 192.168.50.2;
}
    
subnet 10.20.0.0 netmask 255.255.255.0 {
    
    range 10.20.0.100 10.20.0.200;

    option subnet-mask 255.255.255.0;
    option broadcast-address 10.20.0.255;
    option routers 10.20.0.1;

    option domain-name "dhcp-lab.local";
    option domain-name-servers 192.168.50.2;
}
