options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };

    allow-query {
        localhost;
        192.168.10.0/24;
        192.168.20.0/24;
    };

    recursion no;
};

include "/etc/bind/named.conf.local";
